name: Check

on:
  workflow_dispatch:
  push:
    branches:
      - development
  pull_request:

jobs:
  test:
    uses: intisy/workflows/.github/workflows/test.yml@main
    with:
      node_install: npm ci
      node_build: npm run build
      node_test: ""
