name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: intisy/workflows/.github/workflows/deploy-cloudflare.yml@main
    with:
      node_install: npm ci
      checks: |
        npm run typecheck
        npm run fetch-db
        npm run build
      command: deploy
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
